
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - db_data:/app/db
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=super-dev-secret
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
